### ISSUE TITLE
Review full tutorial for how-to guide

### ISSUE THREAD

**Issue by vickytnz** [nhsuk/nhsuk.service-manual.prototype-kit.docs#129]
Review of the journey after the load of changes. 

#96 
#105 
#106 
#108 
#112 
#113

**Comment by anandamaryon1** [comment]
@vickytnz To save another barrage of issues I'll comment on here… 

I've rechecked the tutorial after your changes. Thanks for sorting them, looking much better now. 

I did find a few more issues though:
* On this page: https://prototype-kit.service-manual.nhs.uk/how-tos/build-basic-prototype/use-components the code sample and screenshot doesn't align. (needs a step to change the radio options to just yes/no/I'm not sure
* On this one: https://prototype-kit.service-manual.nhs.uk/how-tos/build-basic-prototype/use-components-2 step one mentions the `govuk` name-spaced component
* On this page: https://prototype-kit.service-manual.nhs.uk/how-tos/build-basic-prototype/branching in step one it mentioned `content.html` but the file is actually named `content-page.html`
* Unless I missed it, I don't think there is a step to fix the back-links, which currently link back to the template folder page versions, making it a bit confusing if you forget to hook them all up. Maybe it could be a bonus task at the end? "Now go and fix your back links using what you've learned about linking pages".

**Comment by vickytnz** [comment]
- [ ] On this page: https://prototype-kit.service-manual.nhs.uk/how-tos/build-basic-prototype/use-components the code sample and screenshot doesn't align. (needs a step to change the radio options to just yes/no/I'm not sure
- [ ] On this one: https://prototype-kit.service-manual.nhs.uk/how-tos/build-basic-prototype/use-components-2 step one mentions the govuk name-spaced component
- [ ] On this page: https://prototype-kit.service-manual.nhs.uk/how-tos/build-basic-prototype/branching in step one it mentioned content.html but the file is actually named content-page.html
- [ ]  Unless I missed it, I don't think there is a step to fix the back-links, which currently link back to the template folder page versions, making it a bit confusing if you forget to hook them all up. Maybe it could be a bonus task at the end? "Now go and fix your back links using what you've learned about linking pages".
