### ISSUE TITLE
Bug: update reference to a govuk HTML class

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk.service-manual.prototype-kit.docs#130]
I notice that this page has a reference to a gov style: https://prototype-kit.service-manual.nhs.uk/how-tos/build-basic-prototype/show-users-answers.

<div class="govuk-summary-list__row">

I'm guessing that it should be an nhs style. 

Thanks

**Comment by vickytnz** [comment]
On review it's just unnecessary as the following line covers it (which is why I missed taking it out). Removed.
