### ISSUE TITLE
Orphan pages in the install guide

### ISSUE THREAD

**Issue by vickytnz** [nhsuk/nhsuk.service-manual.prototype-kit.docs#133]
While looking at pages, I found 2 pages that do not seem to be used and both of which I think we should delete:

## 1. Requirements

This is on https://prototype-kit.service-manual.nhs.uk/install/requirements

![requirements page](https://github.com/user-attachments/assets/68307a43-5639-4cd3-877b-b348811ece8a)

There are versions like this in the GOV.UK Prototype Kit for [windows](https://prototype-kit.service.gov.uk/docs/install/requirements-windows), [mac](https://prototype-kit.service.gov.uk/docs/install/requirements-mac), and [linux](https://prototype-kit.service.gov.uk/docs/install/requirements-linux).

## 2. Where to keep prototypes

This is on https://prototype-kit.service-manual.nhs.uk/install/where-to-keep

![page of where to keep prototypes](https://github.com/user-attachments/assets/8330115c-327f-44a9-88da-803b45a03034)

There is nothing similar in the GOV.UK Prototype Kit.

**Comment by anandamaryon1** [comment]
Yep looks like they can be removed, good find 👍 

Taking a look at them I found this one too: https://prototype-kit.service-manual.nhs.uk/install/windows/git-bash
![image](https://github.com/user-attachments/assets/f98b3461-0b9e-4e67-a2ff-4b1abeefdb5d)

And this one too: https://prototype-kit.service-manual.nhs.uk/install/download
![image](https://github.com/user-attachments/assets/b5037295-2fae-439f-ad85-6ffb57679f94)

**Comment by anandamaryon1** [comment]
In fact, maybe all the guide pages in `/install` that are duplicated in `/mac` and `/windows`?

**Comment by vickytnz** [comment]
All of the windows and mac install pages use a shared parent page that lives on the /install/ folder and is mostly the same but with some blocks that the child pages have content on, for example :

* `/install/download` is used as a parent page for both `/install/mac/download `and `/install/windows/download` with the parent page having some blocks that are then filled in on the child pages. 

I hadn't touched them since in a way it makes sense to have some reusable code, but the particular setup now makes it a pain - at the least I think I'll move all of the shared install base pages into an /includes folder and update the links to make sure we've got better visibility of all of the pages but will wait until after Sara has done the content review just in case it includes these pages.
