### ISSUE TITLE
Set up domain name

### ISSUE THREAD

**Issue by frankieroberto** [nhsuk/nhsuk.service-manual.prototype-kit.docs#16]
Need to put the documentation on a `.nhs.uk` domain name to make it clearer that it is official and to try and avoid the pages being flagged by browsers for potential phishing (see #7).

Agreed name is `prototype-kit.service-manual.nhs.uk`.

**Comment by edwardhorsford** [comment]
GOV.UK Looks to use `prototype-kit`. We could follow suit or else use one of `prototype-kit-documentation` or `prototype-kit-docs`?

**Comment by frankieroberto** [comment]
I don’t think it needs to contain `docs` or `documentation`?  

It could be `prototype-kit.service-manual.nhs.uk` to link it to the service manual?

Or `prototype-kit.england.nhs.uk` or `prototype-kit.digital.nhs.uk` or some other subdomain?

**Comment by anandamaryon1** [comment]
To be clear: it would not need the `docs` because it'll now just link to the GitHub repo for the actual kit? 

I prefer `prototype-kit.service-manual.nhs.uk` as that links it to service manual and follows gov.

**Comment by frankieroberto** [comment]
@anandamaryon1 yep exactly - it’d replace the current site at https://nhsuk-prototype-kit.azurewebsites.net 

The zip file that contains the kit itself would continue to be served by GitHub - just now from a separate repository from the website.

**Comment by frankieroberto** [comment]
Ok let's go with `prototype-kit.service-manual.nhs.uk` 👍

**Comment by frankieroberto** [comment]
This is done: https://prototype-kit.service-manual.nhs.uk 🎉
