### ISSUE TITLE
Style guide for prototype kit instructions

### ISSUE THREAD

**Issue by vickytnz** [nhsuk/nhsuk.service-manual.prototype-kit.docs#62]
As lots of us work on the same set of instructions, some form of MVP style guide would help me and possibly others. 

## Terms so far I've noticed that I'd like documented

* NHS.UK prototype kit - the things that is has to have the NHS.UK together (not just NHS.UK) and how we talk about it after initially mentioning it ('the kit' seems to be what has been decided).
* GOV.UK Prototype Kit and GOV.UK Design System - admittedly not even documented in their own stuff maybe?
* NHS.UK frontend - this is probably defined somewhere else - maybe just linking to it
* Visual Studio Code - after installing things myself I think that it's not helpful to call it VSCode as that's not what it's called and doesn't even show up in computer searches.
* other things like 'command line' and 'terminal' etc - is it 'the terminal' and so on.

## Where this list could live

* in github e.g. part of README - could be a good starting point as it's only needed for the contributors
* in the actual documentation, for example part of contributing - could be a good place to live as there probably aren't too many phrases
* part of the NHS.UK service manual - maybe end game? and some of our stuff may be too niche

## Other thoughts
This is perhaps something that the GOV.UK Design System team could lead on or we start and hand over to them? This feels like a bit of a mix of style guide but also technical writing as this is very much technically focused.

**Comment by frankieroberto** [comment]
Sounds good. I think @sarawilcox and @anandamaryon1 may be able to help with some of this.

Terminal vs command line is a good one to ponder. I'm not sure either is particularly accessible to beginners! It’s also Command Prompt in Windows, although the GOV.UK guide [suggests installing GitBash instead](https://prototype-kit.service.gov.uk/docs/install/requirements-windows) as it’s more similar to Terminal and other unix-based command prompts.

@edwardhorsford any thoughts from your years of running training courses?
