### ISSUE TITLE
Add changelog or history to prototype kit documents

### ISSUE THREAD

**Issue by vickytnz** [nhsuk/nhsuk.service-manual.prototype-kit.docs#65]
As more people are adding things, it will be helpful to know what has been added and when in an easier way than looking at github commits. 

A few options:
* add notes to README.md or something similar - minimum version 
* add a history page in the site  - could be helpful also for those curious about contributing but not keen enough to go straight into github
* create releases in github - probably not needed as no one is really rolling back?
* add to general prototype kit CHANGELOG - consolidated but may be less relevant to people just using the kit

**Comment by frankieroberto** [comment]
I'm not sure - I think the GitHub history is kinda good enough, especially as our pull requests have had some good descriptions (with screenshots!) so far. When you squash-merge the pull request descriptions are used as the commit description, with a link back to the pull request.

That said, I'm not averse to a changelog within this repo to document any major changes to the documentation website.

The prototype kit itself has releases and release notes, as well as a changelog.

**Comment by frankieroberto** [comment]
@vickytnz I wonder if this could be covered by #101 - which I’d envisaged as a "What’s new" page for the kit itself, but could also mention significant changes to the documentation website?
