### ISSUE TITLE
Some pages flagging as Dangerous on Chrome

### ISSUE THREAD

**Issue by vickytnz** [nhsuk/nhsuk.service-manual.prototype-kit.docs#7]
# Bug Report

## What is the issue?

When going on some pages they show up as dangerous

## What steps are required to reproduce the issue?

Go to any of the pages replicating the nhs website :
* https://nhsuk-prototype-kit.azurewebsites.net/templates/nhsuk-healthaz
* https://nhsuk-prototype-kit.azurewebsites.net/templates/nhsuk-mentalhealth
* https://nhsuk-prototype-kit.azurewebsites.net/templates/nhsuk-livewell
* https://nhsuk-prototype-kit.azurewebsites.net/templates/nhsuk-socialcare
* https://nhsuk-prototype-kit.azurewebsites.net/templates/nhsuk-pregnancy
* https://nhsuk-prototype-kit.azurewebsites.net/templates/nhsuk-nhs-services
* https://nhsuk-prototype-kit.azurewebsites.net/templates/nhsuk-coronavirus-hub

It is possible to bypass them (for now) by clicking the link in show details but still not great.

<img width="899" alt="Page with 'dangerous site' and options to view more details or go back to safety" src="https://github.com/user-attachments/assets/18333e32-7574-4572-91ab-6e5a9f3e8116">

## What was the environment where this issue occurred?

* Device: Macbook
* Operating System: Mac Sequoia
* Browser: Google Chrome

## Is there anything else you think would be useful in recreating the issue?

GOV.UK had some issues with login prototype pages in the past, particularly with Chrome

**Comment by vickytnz** [comment]
err ... won't this just be a problem for anyone doing prototype testing on heroku domains (unless it gets set up with custom prototype domains like HMRC did for a while?) with one login it was so bad that we had to skip pages for a while

**Comment by frankieroberto** [comment]
Possibly!? As I understand it, the warning in Chrome is based entirely on unknowable heuristics, so is hard to predict!  Possibly prototypes behind a password might be safer (although I think the heuristics run client-side so perhaps not?).

The pages linked to above likely trigger the warning as they're deliberately exact copies of pages on the NHS website. You can report it as a false-positive but not sure how quickly that updates...

Perhaps sticking a 'this is an example page' banner at the top would help?

**Comment by frankieroberto** [comment]
@vickytnz this seems to have resolved itself somehow - the links no longer flag as dangerous for me in Chrome or Safari, even on the Azure URLs.

In any case, the new nhs.uk should fix it. But we can re-open this again in future if it recurs.
