### ISSUE TITLE
Reference instructions for installing on NHS corporate laptops.

### ISSUE THREAD

**Issue by edwardhorsford** [nhsuk/nhsuk.service-manual.prototype-kit.docs#8]
People on NHS corporate laptops have been [given specific instructions](https://nhs.sharepoint.com/sites/X26_URPG/SitePages/get-research-and-design-tools.aspx#:~:text=NHS%20UK%20Prototyping%20Kit) (sharepoint link) for installation / permissions. We should consider either linking to the guidance, or including in the rendered instructions.

**Comment by frankieroberto** [comment]
@paulmsmith did it work? 🤞
