### ISSUE TITLE
Findability of the prototype kit how to guides

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk.service-manual.prototype-kit.docs#9]
## What

Review the findability of the prototype kit 'how to' guides.

## Why

People have difficulty finding the guides, resulting in time being wasted.

**Comment by davidhunter08** [comment]
@frankieroberto (sorry I missed your comment!) -  I think it stemmed from questions popping up on Slack around how to do things in the prototype kit (eg: branching, passing data etc). When we answered the questions by sharing links to the docs, people said that they didn't the docs existed. The guides were on that URL (https://nhsuk-prototype-kit.azurewebsites.net/docs) at the time.

**Comment by frankieroberto** [comment]
@davidhunter08 ah thanks! Something to think about - guess we’ll need to promote it a fair bit more!

**Comment by frankieroberto** [comment]
@vickytnz @davidhunter08  are we happy that this is done for now, or is there any more to be done to improve findability?
