### ISSUE TITLE
Create a standalone page for Support

### ISSUE THREAD

**Issue by frankieroberto** [nhsuk/nhsuk.service-manual.prototype-kit.docs#91]
Currently we have an [About page](https://prototype-kit.service-manual.nhs.uk/about) which contains some information about Support.

I think it might be worth having a standalone page for Support, which could then go into a few more details?

As well as linking to the `#prototype-kit` Slack channel on the service manual Slack, it could _also_ link to the `#prototype-kit` channel on the NHS England Slack (for NHS England staff and workers only). Might be a bit confusing, but could reduce friction for people in one Slack but not the other?

We could also link to GitHub issues as another avenue for people to get support, eg if they have a suspect bug.

**Comment by vickytnz** [comment]
Provisional start for extended page

# Support

The NHS prototype kit is maintained by NHS England. If you've got a question or need support you can:

* [email us](mailto:england.service-manual@nhs.net?subject=NHS%20prototype%20kit%20-%20About)
* use Slack - if you have an NHS England email or have been given access to the NHS England slack instance you can use the [NHS England #prototype-kit slack channel](https://nhsdigitalcorporate.enterprise.slack.com/archives/C042J3MTJG2). If you do not you can also use the [ NHS digital service manual #prototype-kit Slack channel](https://nhs-service-manual.slack.com/messages/CFYL2GDGW)
* add a bug or view issues on on GitHub for the [prototype kit](https://github.com/nhsuk/nhsuk-prototype-kit/issues) or  [this documentation site](https://github.com/nhsuk/nhsuk.service-manual.prototype-kit.docs/issues)  

You can also get involved with [contributing](/contributing).
