### ISSUE TITLE
Add navigation menu?

### ISSUE THREAD

**Issue by vickytnz** [nhsuk/nhsuk.service-manual.prototype-kit.docs#93]
Using a structure like [NHS notify](https://notify.nhs.uk/) would allow us to both have a consistent navigation and also free up the area underneath the hero image to have key benefits.

![image from govuk notifiy](https://github.com/user-attachments/assets/37834754-d196-4a24-b6da-9e11204e0862)

**Comment by vickytnz** [comment]
A mockup of navigation.

![NHS.UK prototype kit page of benefits underneath](https://github.com/user-attachments/assets/b9e5a264-cb91-4810-a20a-ec758b9e0c94)

**Comment by frankieroberto** [comment]
I like this idea (and I also tried this out locally) but I think we should settle on the Information architecture first?

I'm not yet sure whether Templates should stay on the documentation site or be in the kit only or remain in both - see #60 

Also had an idea that we could add Support (#91) and Contribution (#92) pages which could then go in the nav?

Also do we want to stick with 'How to guides' or pick another label for that? 🤷

**Comment by vickytnz** [comment]
Closing this issue as I think it is covered by other thigns
