### ISSUE TITLE
Page templates page does not include correct folder path

### ISSUE THREAD

**Issue by vickytnz** [nhsuk/nhsuk.service-manual.prototype-kit.docs#96]
# Bug Report

## What is the issue

The page templates page https://prototype-kit.service-manual.nhs.uk/page-templates has incorrect information for people using the prototype on their own computers - it does not live in `/views/templates` as suggested but `/docs/views/templates` 

## Suggested actions

1. correct file path from `/views/templates` to `docs/views/templates`

**Comment by frankieroberto** [comment]
Opps. Let's fix the paths and make all the links from the example templates just be `href="#"`?

Longer-term see  #60 for giving this whole section a bit more thought.

**Comment by frankieroberto** [comment]
@vickytnz I've moved the link issue to #110 if that's ok, so that this issue can purely be about the error in the folder path.
